name: Build and push Node image to Docker Hub

on:
  workflow_call:
    inputs:
      image-name:
        description: "Docker image name, including tag"
        required: true
        type: string
      ci-pipelines-ref:
        description: "Ref (branch/tag/SHA) of ci-pipelines to use for the Dagger module"
        required: false
        default: "main"
        type: string
      platforms:
        description: "Target image platforms, comma separated"
        required: false
        default: "linux/arm64"
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-24.04-arm

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: Checkout ci-pipelines (self)
        uses: actions/checkout@v6.0.2
        with:
          repository: dario-mr/ci-pipelines
          ref: ${{ inputs.ci-pipelines-ref }}
          path: .ci-pipelines

      - name: Install Dagger CLI
        uses: ./.ci-pipelines/.github/actions/setup-dagger

      - name: Run "Node Build and Push" with Dagger
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          dagger call \
            --mod github.com/dario-mr/ci-pipelines@${{ inputs.ci-pipelines-ref }} \
            build-and-push-node \
            --source . \
            --docker-username "${{ secrets.DOCKERHUB_USERNAME }}" \
            --docker-password env://DOCKERHUB_TOKEN \
            --image-name "${{ inputs.image-name }}" \
            --platforms "${{ inputs.platforms }}"
