name: Build and push Node image to Docker Hub

on:
  workflow_call:
    inputs:
      image-repo:
        description: "Docker image repository (without tag), e.g. dariomr8/frontend-app"
        required: true
        type: string
      ci-pipelines-ref:
        description: "Ref (branch/tag/SHA) of ci-pipelines to use for the Dagger module"
        required: false
        default: "main"
        type: string
      platforms:
        description: "Target image platforms, comma separated"
        required: false
        default: "linux/arm64"
        type: string
      dockerfile:
        description: "Dockerfile path relative to the repository root"
        required: false
        default: "Dockerfile"
        type: string
      runner-label:
        description: "GitHub Actions runner label"
        required: false
        default: "ubuntu-24.04-arm"
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build_and_push:
    runs-on: ${{ inputs.runner-label }}

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: Checkout ci-pipelines (self)
        uses: actions/checkout@v6.0.2
        with:
          repository: dario-mr/ci-pipelines
          ref: ${{ inputs.ci-pipelines-ref }}
          path: .ci-pipelines

      - name: Install Dagger CLI
        uses: ./.ci-pipelines/.github/actions/setup-dagger

      - name: Run "Node Build and Push" with Dagger
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          dagger call \
            --mod github.com/dario-mr/ci-pipelines@${{ inputs.ci-pipelines-ref }} \
            build-and-push-node \
            --source . \
            --docker-username "${{ secrets.DOCKERHUB_USERNAME }}" \
            --docker-password env://DOCKERHUB_TOKEN \
            --image-repo "${{ inputs.image-repo }}" \
            --event-name "${{ github.event_name }}" \
            --commit-sha "${{ github.sha }}" \
            --dockerfile "${{ inputs.dockerfile }}" \
            --platforms "${{ inputs.platforms }}"
